# Generated by Django 4.0.5 on 2022-06-27 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DRF', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profession',
            name='user',
        ),
        migrations.AddField(
            model_name='profession',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, to='DRF.user'),
        ),
    ]
