# Generated by Django 4.0.5 on 2022-06-27 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DRF', '0002_remove_profession_user_profession_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profession',
            name='user',
        ),
        migrations.AddField(
            model_name='profession',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DRF.user'),
        ),
    ]
